#!/usr/bin/env python
"""Build a sourceless .pyc obfuscated Python release from a project directory.

Usage examples:
  python scripts/obfuscate_project.py . -O ../fpbrowser2api_public
  python scripts/obfuscate_project.py . --keep src/api/routes.py --keep src/services/veo_workflow_executor.py

It compiles Python source files to legacy importable .pyc files and does not
copy the original .py files, except paths explicitly passed with --keep.
This is lightweight obfuscation, not encryption. Build and runtime must use the
same CPython major/minor version, e.g. build with 3.13 and run with 3.13.x.
"""

from __future__ import annotations

import argparse
import fnmatch
import os
import py_compile
import shutil
import sys
import textwrap
from pathlib import Path

DEFAULT_EXCLUDE_DIRS = {
    ".git", ".hg", ".svn", "__pycache__", ".pytest_cache", ".mypy_cache",
    ".ruff_cache", "venv", ".venv", "env", ".env", "node_modules",
}
DEFAULT_EXCLUDE_GLOBS = ["*.pyc", "*.pyo", "*.log", "*.pid", "*.out", "*.out.err"]
RUNTIME_DIRS = ["data", "logs", "analyze"]
SECRET_DEFAULTS = ["config/setting.toml"]


def norm_rel(p: str | Path) -> Path:
    s = str(p).replace("\\", "/").strip().strip("/")
    return Path(s)


def rel_posix(p: Path) -> str:
    return p.as_posix()


def is_relative_to(child: Path, parent: Path) -> bool:
    try:
        child.relative_to(parent)
        return True
    except ValueError:
        return False


def ensure_safe_output(src_root: Path, output: Path) -> Path:
    src_root = src_root.resolve()
    output = output.expanduser().resolve()
    if output == src_root:
        raise SystemExit(f"拒绝把输出目录设为源码目录: {output}")
    if is_relative_to(output, src_root):
        raise SystemExit(f"拒绝把输出目录放在源码目录内部，避免清理时误删: {output}")
    if output.anchor == str(output):
        raise SystemExit(f"拒绝使用磁盘根目录作为输出: {output}")
    return output


def should_skip(rel: Path, excluded_dirs: set[str], excluded_globs: list[str]) -> bool:
    parts = set(rel.parts)
    if parts & excluded_dirs:
        return True
    posix = rel_posix(rel)
    return any(fnmatch.fnmatch(posix, pat) or fnmatch.fnmatch(rel.name, pat) for pat in excluded_globs)


def compile_to_pyc(src: Path, dst_pyc: Path, dfile: str, optimize: int) -> None:
    dst_pyc.parent.mkdir(parents=True, exist_ok=True)
    py_compile.compile(str(src), cfile=str(dst_pyc), dfile=dfile, doraise=True, optimize=optimize)


def write_main_stub(output: Path, main_name: str) -> None:
    major, minor = sys.version_info[:2]
    stub = f'''\
"""Sourceless launcher. Generated by scripts/obfuscate_project.py."""
from __future__ import annotations
import importlib.util
import pathlib
import sys

REQUIRED = ({major}, {minor})


def _run_pyc() -> None:
    if sys.implementation.name != "cpython" or sys.version_info[:2] != REQUIRED:
        raise SystemExit(
            "This release was built for CPython "
            f"{{REQUIRED[0]}}.{{REQUIRED[1]}}.x, current is {{sys.version.split()[0]}}."
        )
    pyc = pathlib.Path(__file__).with_suffix(".pyc")
    spec = importlib.util.spec_from_file_location("__main__", pyc)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to load {{pyc}}")
    module = importlib.util.module_from_spec(spec)
    sys.modules["__main__"] = module
    spec.loader.exec_module(module)


if __name__ == "__main__":
    _run_pyc()
'''
    (output / main_name).write_text(stub, encoding="utf-8", newline="\n")


def write_readme(output: Path, kept: set[Path]) -> None:
    major, minor = sys.version_info[:2]
    kept_lines = "\n".join(f"- `{rel_posix(p)}`" for p in sorted(kept)) or "- 无"
    readme = f"""\
# Obfuscated Python Release

此目录由 `scripts/obfuscate_project.py` 生成：大多数 `.py` 已编译为可直接导入的 legacy `.pyc`，源码未复制。

保留源码文件：
{kept_lines}

注意：这是轻量混淆，不是强加密；适合提高阅读和修改门槛。

Python 版本要求：构建使用 **CPython {major}.{minor}.x**，部署运行也必须使用 **CPython {major}.{minor}.x**。同一份发布包可在 Windows/Ubuntu 运行，但 Python 主/次版本必须一致。
"""
    p = output / "OBFUSCATED_README.md"
    p.write_text(readme, encoding="utf-8", newline="\n")


def main() -> int:
    ap = argparse.ArgumentParser(description="Obfuscate Python project into sourceless .pyc release")
    ap.add_argument("src_dir", type=Path, help="项目目录")
    ap.add_argument("-O", "--output", type=Path, required=True, help="输出目录")
    ap.add_argument("--keep", action="append", default=[], help="不混淆/保留源码的相对路径，可重复")
    ap.add_argument("--exclude-dir", action="append", default=[], help="额外排除目录名，可重复")
    ap.add_argument("--exclude-glob", action="append", default=[], help="额外排除 glob，可重复，如 data/*.db")
    ap.add_argument("--secret", action="append", default=[], help="不复制的敏感相对路径，可重复")
    ap.add_argument("--main", default="main.py", help="入口 py 文件；会生成同名 stub + .pyc，默认 main.py")
    ap.add_argument("--optimize", type=int, choices=[0, 1, 2], default=2, help="py_compile optimize 级别，默认 2")
    ap.add_argument("--no-clean", action="store_true", help="不清空输出目录")
    args = ap.parse_args()

    if sys.implementation.name != "cpython":
        raise SystemExit("此方式需要 CPython。")

    src_root = args.src_dir.resolve()
    if not src_root.is_dir():
        raise SystemExit(f"项目目录不存在: {src_root}")
    output = ensure_safe_output(src_root, args.output)
    keep = {norm_rel(x) for x in args.keep}
    secrets = {norm_rel(x) for x in (SECRET_DEFAULTS + args.secret)}
    excluded_dirs = DEFAULT_EXCLUDE_DIRS | set(args.exclude_dir)
    excluded_globs = DEFAULT_EXCLUDE_GLOBS + args.exclude_glob
    main_rel = norm_rel(args.main)

    print(f"Source: {src_root}")
    print(f"Output: {output}")
    print(f"Python: {sys.version.split()[0]} ({sys.implementation.name})")
    print("Keep source:", ", ".join(map(rel_posix, sorted(keep))) or "<none>")

    if output.exists() and not args.no_clean:
        shutil.rmtree(output)
    output.mkdir(parents=True, exist_ok=True)

    copied = compiled = skipped = 0
    for src in sorted(src_root.rglob("*")):
        rel = src.relative_to(src_root)
        if should_skip(rel, excluded_dirs, excluded_globs):
            skipped += 1
            continue
        if rel in secrets:
            skipped += 1
            continue
        dst = output / rel
        if src.is_dir():
            dst.mkdir(parents=True, exist_ok=True)
            continue
        if src.suffix == ".py" and rel not in keep:
            compile_to_pyc(src, dst.with_suffix(".pyc"), rel_posix(rel), args.optimize)
            compiled += 1
            if rel == main_rel:
                write_main_stub(output / rel.parent, rel.name)
            continue
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        copied += 1

    for d in RUNTIME_DIRS:
        p = output / d
        p.mkdir(parents=True, exist_ok=True)
        (p / ".gitkeep").touch()

    write_readme(output, keep)
    sh = output / "fpbrowser2api_service.sh"
    if sh.exists():
        try:
            os.chmod(sh, os.stat(sh).st_mode | 0o755)
        except OSError:
            pass

    print(f"OK: compiled={compiled}, copied={copied}, skipped={skipped}")
    print("提示：发布包必须用相同 CPython 主/次版本运行。")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
